### ISSUE TITLE
Error chmod

### ISSUE THREAD

**Issue by stiig** [puphpet/puphpet#1653] opened 2015-05-21 16:47 UTC
First vagrant up if i use `sync_type: smb`
[config.yaml, full error log and succes log](https://gist.github.com/stiig/b279bf4c7f0ab42b2272)
output error:
```
==> default: Notice: /Stage[main]/Main/Exec[Create apache webroot]/returns: chown: changing ownership of `/var/www': Permission denied
==> default: Error: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[Create apache webroot]/returns: change from notrun to 0 failed: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
```
if i change `sync_type: smb` to `sync_type: default` - everything all right

**Comment by jtreminio** [comment] 2015-05-21 16:50
Dupe of #1631

**Closed by jtreminio** 2015-05-21 16:50 UTC
