### ISSUE TITLE
elasticsearch not running/startup script is missing

### ISSUE THREAD

**Issue by bartrail** [puphpet/puphpet#2079] opened 2015-12-31 13:56 UTC
elasticsearch is installed to `/usr/share/elasticsearch` 
but the script like `/etc/init.d/elasticsearch` is missing and I can't start it with `service elasticsearch start` because the _service elasticsearch is not recognized_  - 

besides that, the box is running fine..

this is my config.yaml http://pastebin.com/ZHvM6aHc

Any help is very appreciated :)

**Comment by vincenzo** [comment] 2016-01-06 17:22
This is a duplicate of https://github.com/puphpet/puphpet/issues/2040

**Closed** 2016-01-16 05:51 UTC
