### ISSUE TITLE
Cannot install Xdebug

### ISSUE THREAD

**Issue by Mango-Design** [puphpet/puphpet#2191] opened 2016-02-25 01:06 UTC
I've tried the same configuration without Xdebug and it works nicely.
I've tried to enable xdebug both with PHP 5.6 and 5.5 with the same result, shown below
```
vagrant provision
==> virtual: Running provisioner: shell...
    virtual: Running: inline script
==> virtual: Running provisioner: shell...
    virtual: Running: C:/Users/XXXXX/AppData/Local/Temp/vagrant-shell20160225-6232-c3f3ce.sh
==> virtual: 
==> virtual:  ____        ____  _   _ ____      _      generated using
==> virtual: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> virtual: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> virtual: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> virtual: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> virtual: Running provisioner: shell...
    virtual: Running: C:/Users/XXXXX/AppData/Local/Temp/vagrant-shell20160225-6232-1ubb0rc.sh
==> virtual: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> virtual: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> virtual: Adding generated root key to /root/.ssh/id_rsa
==> virtual: Adding generated root key to /root/.ssh/id_rsa.pub
==> virtual: Adding generated root key to /root/.ssh/authorized_keys
==> virtual: Adding generated key to /home/vagrant/.ssh/id_rsa
==> virtual: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> virtual: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> virtual: Running provisioner: shell...
    virtual: Running: C:/Users/XXXXX/AppData/Local/Temp/vagrant-shell20160225-6232-na443u.sh
==> virtual: Running provisioner: shell...
    virtual: Running: C:/Users/XXXXX/AppData/Local/Temp/vagrant-shell20160225-6232-vcnhpy.sh
==> virtual: Successfully installed deep_merge-1.0.1
==> virtual: Successfully installed activesupport-4.2.5.1
==> virtual: Successfully installed vine-0.2
==> virtual: 3 gems installed
==> virtual: Running provisioner: shell...
    virtual: Running: C:/Users/XXXXX/AppData/Local/Temp/vagrant-shell20160225-6232-qc5llp.sh
==> virtual: Running files in files/exec-preprovision
==> virtual: Finished running files in files/exec-preprovision
==> virtual: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-preprovision-ran or the whole file to rerun all
==> virtual: Running provisioner: puppet...
==> virtual: Running Puppet with ...
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Info: Loading facts
==> virtual: Warning: Scope(Apt::Source[mariadb]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> virtual: Warning: Scope(Apt::Source[nginx]): $key_source is deprecated and will be removed in the next major release, please use $key => { 'source' => http://nginx.org/keys/nginx_signing.key } instead.
==> virtual: Warning: Scope(Apt::Key[Add key: 7BD9BF62 from Apt::Source nginx]): $key_source is deprecated and will be removed in the next major release. Please use $source instead.
==> virtual: Notice: Compiled catalog for virtual.puphpet in environment production in 3.75 seconds
==> virtual: Warning: Found multiple default providers for vcsrepo: bzr, cvs, dummy, git, hg, svn; using bzr
==> virtual: Warning: /Apt_key[Add key: 7BD9BF62 from Apt::Source nginx]: The id should be a full fingerprint (40 characters), see README.
==> virtual: Info: Applying configuration version '1456362198'
==> virtual: Notice: /Stage[main]/Puphpet_mariadb/Exec[Set pidfile parent directory permissions]/returns: executed successfully
==> virtual: Notice: /Stage[main]/Puphpet_server/Exec[dotfiles]/returns: executed successfully
==> virtual: Info: Computing checksum on file /etc/timezone
==> virtual: Info: FileBucket got a duplicate file {md5}4f24b133ba38d8fd565168742c9aedeb
==> virtual: Info: /Stage[main]/Timezone/File[/etc/timezone]: Filebucketed /etc/timezone to puppet with sum 4f24b133ba38d8fd565168742c9aedeb
==> virtual: Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: content changed '{md5}4f24b133ba38d8fd565168742c9aedeb' to '{md5}ae1d80ba85332ae2d9fbbd491b17c043'
==> virtual: Info: /Stage[main]/Timezone/File[/etc/timezone]: Scheduling refresh of Exec[update_timezone]
==> virtual: Notice: /Stage[main]/Timezone/Exec[update_timezone]: Triggered 'refresh' from 1 events
==> virtual: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[copy xdebug.so to modules dir]/returns: cp: cannot create regular file â€˜${prefix}/lib/php/20131226/xdebug.soâ€™: No such file or directory
==> virtual: Error: cp /.puphpet-stuff/xdebug/modules/xdebug.so `php-config --extension-dir`/xdebug.so                   && touch /.puphpet-stuff/xdebug-installed returned 1 instead of one of [0]
==> virtual: Error: /Stage[main]/Puphpet::Php::Xdebug/Exec[copy xdebug.so to modules dir]/returns: change from notrun to 0 failed: cp /.puphpet-stuff/xdebug/modules/xdebug.so `php-config --extension-dir`/xdebug.so                   && touch /.puphpet-stuff/xdebug-installed returned 1 instead of one of [0]
==> virtual: Info: Computing checksum on file /etc/localtime
==> virtual: Info: FileBucket got a duplicate file {md5}c79354b8dbee09e62bbc3fb544853283
==> virtual: Info: /Stage[main]/Timezone/File[/etc/localtime]: Filebucketed /etc/localtime to puppet with sum c79354b8dbee09e62bbc3fb544853283
==> virtual: Notice: /Stage[main]/Timezone/File[/etc/localtime]/ensure: ensure changed 'file' to 'link'
==> virtual: Notice: /Stage[main]/Puphpet::Php::Xdebug/Puphpet::Php::Ini[xdebug/zend_extension]/Augeas[XDEBUG/zend_extension: xdebug.so]: Dependency Exec[copy xdebug.so to modules dir] has failures: true
==> virtual: Warning: /Stage[main]/Puphpet::Php::Xdebug/Puphpet::Php::Ini[xdebug/zend_extension]/Augeas[XDEBUG/zend_extension: xdebug.so]: Skipping because of failed dependencies
==> virtual: Notice: /Stage[main]/Puphpet_xdebug/Puphpet::Php::Ini[xdebug.remote_autostart]/Augeas[XDEBUG/xdebug.remote_autostart: 1]/returns: executed successfully
==> virtual: Info: /Stage[main]/Puphpet_xdebug/Puphpet::Php::Ini[xdebug.remote_autostart]/Augeas[XDEBUG/xdebug.remote_autostart: 1]: Scheduling refresh of Service[php5.6-fpm]
==> virtual: Info: Puphpet::Php::Ini[xdebug.remote_autostart]: Scheduling refresh of Service[php5.6-fpm]
==> virtual: Notice: /Stage[main]/Pyenv/Vcsrepo[/usr/local/pyenv]/revision: revision changed '3cde540ca00208fbfd0a5e7708c3053bc8cca9f5' to 'v0.4.0-20140404'
==> virtual: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.6-imagick' returned 100: Reading package lists...
==> virtual: Building dependency tree...
==> virtual: Reading state information...
==> virtual: E: Unable to locate package php5.6-imagick
==> virtual: E: Couldn't find any package by regex 'php5.6-imagick'
==> virtual: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Module[imagick]/Php::Module[imagick]/Package[PhpModule_imagick]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.6-imagick' returned 100: Reading package lists...
==> virtual: Building dependency tree...
==> virtual: Reading state information...
==> virtual: E: Unable to locate package php5.6-imagick
==> virtual: E: Couldn't find any package by regex 'php5.6-imagick'
==> virtual: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]/ensure: created
==> virtual: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]: Scheduling refresh of Service[php5.6-fpm]
==> virtual: Info: Puphpet::Php::Module[mcrypt]: Scheduling refresh of Service[php5.6-fpm]
==> virtual: Notice: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Dependency Exec[copy xdebug.so to modules dir] has failures: true
==> virtual: Notice: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Dependency Package[PhpModule_imagick] has failures: true
==> virtual: Info: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Unscheduling all events on Service[php5.6-fpm]
==> virtual: Info: Class[Puphpet_php]: Unscheduling all events on Class[Puphpet_php]
==> virtual: Info: Stage[main]: Unscheduling all events on Stage[main]
==> virtual: Warning: /Stage[main]/Puphpet_php/Service[php5.6-fpm]: Skipping because of failed dependencies
==> virtual: Notice: Applied catalog in 10.44 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Process finished with exit code 1

```

**Comment by alexmglover** [comment] 2016-02-25 15:46
I'm also having the same issue.  I get the error message "cannot create regular file ‘${prefix}/lib/php/20131226/xdebug.so’".

**Comment by vorozhbit** [comment] 2016-02-25 17:43
Same error:

```
Error: cp /.puphpet-stuff/xdebug/modules/xdebug.so `php-config --extension-dir`/xdebug.so                   && touch /.puphpet-stuff/xdebug-installed returned 1 instead of one of [0]
Error: /Stage[main]/Puphpet::Php::Xdebug/Exec[copy xdebug.so to modules dir]/returns: change from notrun to 0 failed: cp /.puphpet-stuff/xdebug/modules/xdebug.so `php-config --extension-dir`/xdebug.so                   && touch /.puphpet-stuff/xdebug-installed returned 1 instead of one of [0]
```

**Comment by colinodell** [comment] 2016-02-25 18:08
I'm having this issue as well.  This was working fine a couple days ago and I have not changed my .yml file since then.

**Comment by colinodell** [comment] 2016-02-25 18:53
This might be caused by this issue: https://github.com/oerdnj/deb.sury.org/issues/270

**Comment by colinodell** [comment] 2016-02-26 14:17
The underlying issue has been fixed in the latest PHP 7 build.

**Comment by alexmglover** [comment] 2016-02-26 14:36
Unfortunately, I can't switch to PHP 7.  Do you know if this has been fixed in any other builds?

**Comment by colinodell** [comment] 2016-02-26 14:41
@alexmglover You can test by running `vagrant destroy` and then `vagrant up`.

Alternatively, if you don't want to risk destroying the VM until you're 100% sure the issue is fixed, do the following:

1. `vagrant ssh` into the box.
2. Run `php-config --extension-dir` and confirm that it outputs `${prefix}/lib/php/20131226/xdebug.so`
3. Upgrade PHP via `apt-get`
4. Run `php-config --extension-dir` again.  If the `${prefix}` is gone then the issue is definitely fixed.

**Comment by jtreminio** [comment] 2016-03-05 04:56
Fixed upstream.

**Closed by jtreminio** 2016-03-05 04:56 UTC
