### ISSUE TITLE
(vagrant up) Many errors like this: "Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install mysql-community-server' returned 1"

### ISSUE THREAD

**Issue by sugalvojau** [puphpet/puphpet#2408] opened 2016-08-17 02:28 UTC
I am on Windows 10 Pro + [VirtualBox-5.1.2-108956-Win.exe](http://download.virtualbox.org/virtualbox/5.1.2/VirtualBox-5.1.2-108956-Win.exe) + [vagrant_1.8.5.msi](https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5.msi)
I try to `vagrant up` on this project: [https://github.com/sugalvojau/veikt.dev.git](https://github.com/sugalvojau/veikt.dev.git)

And I get bunch of errors like this:
`Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install mysql-community-server' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again`

Here is the full vagrant up log I get every time I do `vagrant up`: [vagrant_up_log.txt](https://github.com/puphpet/puphpet/files/421632/vagrant_up_log.txt)

Can't quickly find and fix the reason of these errors...
Can somebody check if the same error exists on their machine? Would be nice if anybody with similar set of software Windows 10 Pro + [VirtualBox 5.1.2](http://download.virtualbox.org/virtualbox/5.1.2/VirtualBox-5.1.2-108956-Win.exe) + [Vagrant 1.8.5](https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5.msi) would check that.

**Update1:**
- I have tried to uninstall both (Vagrant and VirtualBox, including directories: `~/.vagrant.d`, `~/.VirtualBox`, `~/VirtualBox VMs`) and then install both again (clean install?) - nothing changed.
- I have tried to install (clean install as before) different version of VirtualBox ([VirtualBox-5.0.26-108824-Win.exe](http://download.virtualbox.org/virtualbox/5.0.26/VirtualBox-5.0.26-108824-Win.exe)) - nothing changed.
- I have tried to upload [config.yaml](https://raw.githubusercontent.com/sugalvojau/veikt.dev/master/puphpet/config.yaml) file to [puphpet.com](https://puphpet.com/) and replace files I have with files from the new archive, but again - nothing changed.
- `vagrant provision` does not help.
- Took default set from puphpet.com (however, made the only change - checked MySQL instead of default MariaDB). - this one seems to be working well.

...still can't figure out where is the main cause of these errors.

**Comment by head82** [comment] 2016-08-17 12:18
same on osx with virtualbox5, vagrant 1.8.5, box puphpet/centos65-x64
many errors because of problems with yum and repo repoforgeextras

**Comment by mrx-hackathon-tech** [comment] 2016-08-17 12:52
same on osx with virtualbox5, vagrant 1.8.5, box puphpet/centos65-x64

**Comment by head82** [comment] 2016-08-17 13:11
I have just found out that this is a well known problem. You can find many (puphpet) issues about that. The mirror http://apt.sw.be is down.

**Comment by head82** [comment] 2016-08-17 18:06
just created a pull request with a bugfix: https://github.com/puphpet/puppet-yum/pull/1

**Comment by sugalvojau** [comment] 2016-08-17 19:28
Works just well! Thanks to @mrx-hackathon-tech for checking and thanks to @head82 for checking and quickly fixing! Hope others will benefit from this fix as well.

**Comment by natenolting** [comment] 2016-08-22 13:52
Could this be the cause also of this issue? It looks like **httpd24u** can't be found now:

```
==> site1: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install httpd24u' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again
==> site1: Error: /Stage[main]/Apache/Package[httpd]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install httpd24u' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again
```

**Comment by kielerrr** [comment] 2016-08-23 03:46
Thanks for the fix @head82 hopefully this gets merged asap.. I spent a full day trying to find this issue

**Comment by alvinnguyen** [comment] 2016-08-29 02:05
Thanks guys, this helped a lot.

**Comment by po2go-sean** [comment] 2016-08-29 16:26
We should assist Juan and consolidate all the issue reports into this one, since it has the fix linked. (Also, thank you @head82 !)

**Comment by po2go-sean** [comment] 2016-09-15 21:01
I stand corrected (by myself? by trial and error?)
The bug fix supplied above by @head82 works just fine. I just couldn't find the file(s) initially.
In your extract puphpet directory apply the changes in puphpet/puphpet-yum:f9fd7199716e7cd81e895507dd44e7fa32fa79b0 to the files found here:
puphpet/puppet/modules/yum/manifests/repo/

**Comment by jtreminio** [comment] 2016-10-05 20:11
Fixed in the latest round of puppet refactoring: https://github.com/puphpet/puppet-puphpet/tree/master/manifests/mysql

**Closed by jtreminio** 2016-10-05 20:11 UTC
