### ISSUE TITLE
Error: exception object expected

### ISSUE THREAD

**Issue by engelju** [puphpet/puphpet#1655] opened 2015-05-22 08:45 UTC
I tried setting up a new box with the config files I got from Puphpet and it resulted in an error.

Log output:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puphpet/ubuntu1404-x64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/ubuntu1404-x64'
    default: URL: https://atlas.hashicorp.com/puphpet/ubuntu1404-x64
==> default: Adding box 'puphpet/ubuntu1404-x64' (v2.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/puphpet/boxes/ubuntu1404-x64/versions/2.0/providers/virtualbox.box
==> default: Successfully added box 'puphpet/ubuntu1404-x64' (v2.0) for 'virtualbox'!
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Setting the name of the VM: puphet_default_1432283635908_86902
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 8750 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => /Applications/MAMP/htdocs/__tests/puphet
    default: /vagrant => /Applications/MAMP/htdocs/__tests/puphet
    default: /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b => /Applications/MAMP/htdocs/__tests/puphet/puphpet/puppet/modules
    default: /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a => /Applications/MAMP/htdocs/__tests/puphet/puphpet/puppet
==> default: Running provisioner: shell...
    default: Running: /var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vagrant-shell20150522-46149-frq4oj.sh
==> default: stdin: is not a tty
==> default: 
==> default:  ____        ____  _   _ ____      _      generated using
==> default: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: Running initial-setup apt-get update
==> default: Finished running initial-setup apt-get update
==> default: Running provisioner: shell...
    default: Running: /var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vagrant-shell20150522-46149-1xv16qk.sh
==> default: stdin: is not a tty
==> default: Generating public/private rsa key pair.
==> default: Your identification has been saved in /vagrant/puphpet/files/dot/ssh/root_id_rsa.
==> default: Your public key has been saved in /vagrant/puphpet/files/dot/ssh/root_id_rsa.pub.
==> default: The key fingerprint is:
==> default: ab:1a:92:d6:21:26:7e:00:9d:75:20:73:73:6f:87:06 root@local
==> default: The key's randomart image is:
==> default: +--[ RSA 2048]----+
==> default: |  o =.E          |
==> default: | . * + o .       |
==> default: |. o     = .      |
==> default: |.      o .       |
==> default: |..o .   S        |
==> default: |.o.+ .   .       |
==> default: | .+.o   .        |
==> default: | ... . .         |
==> default: |    ...          |
==> default: +-----------------+
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/root_id_rsa'!
==> default: Generating public/private rsa key pair.
==> default: Your identification has been saved in /vagrant/puphpet/files/dot/ssh/id_rsa.
==> default: Your public key has been saved in /vagrant/puphpet/files/dot/ssh/id_rsa.pub.
==> default: The key fingerprint is:
==> default: 48:9f:c6:df:b7:d9:4e:18:51:15:f7:ea:28:c0:ad:4a root@local
==> default: The key's randomart image is:
==> default: +--[ RSA 2048]----+
==> default: |               .*|
==> default: |               .o|
==> default: |      .       . .|
==> default: |     . = o     o |
==> default: |      . S .   o  |
==> default: |       . + . o o |
==> default: |      E . o o + .|
==> default: |     . .   . . = |
==> default: |      .       o.o|
==> default: +-----------------+
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/id_rsa'!
==> default: Adding generated key to /root/.ssh/id_rsa
==> default: Adding generated key to /root/.ssh/id_rsa.pub
==> default: Adding generated key to /root/.ssh/authorized_keys
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: Running provisioner: shell...
    default: Running: /var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vagrant-shell20150522-46149-8jitw0.sh
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: /var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vagrant-shell20150522-46149-x0iots.sh
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: /var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/vagrant-shell20150522-46149-1grn5i5.sh
==> default: stdin: is not a tty
==> default: Successfully installed deep_merge-1.0.1
==> default: 1 gem installed
==> default: Successfully installed thread_safe-0.3.5
==> default: Successfully installed minitest-5.6.1
==> default: Successfully installed tzinfo-1.2.2
==> default: Successfully installed i18n-0.7.0
==> default: Successfully installed activesupport-4.2.1
==> default: 5 gems installed
==> default: Successfully installed vine-0.0.2
==> default: 1 gem installed
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: stdin: is not a tty
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/composer/lib/facter/composer_home.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/concat/lib/facter/concat_basedir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/firewall/lib/facter/ip6tables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/firewall/lib/facter/iptables_persistent_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/firewall/lib/facter/iptables_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/git/lib/facter/git_exec_path.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/git/lib/facter/git_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/java/lib/facter/java_major_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/java/lib/facter/java_patch_level.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/java/lib/facter/java_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/php/lib/facter/php_fact_extension_dir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/php/lib/facter/php_fact_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/puppi/lib/facter/last_run.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/puppi/lib/facter/puppi_projects.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/puppi/lib/facter/windows_common_appdata.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/rvm/lib/facter/rvm_installed.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/rvm/lib/facter/rvm_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/staging/lib/facter/staging_http_get.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/staging/lib/facter/staging_windir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/stdlib/lib/facter/facter_dot_d.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/stdlib/lib/facter/pe_version.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/stdlib/lib/facter/puppet_vardir.rb
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-8953e541ad1824c9c4a2944c4020a62b/stdlib/lib/facter/root_home.rb
==> default: Error: exception object expected at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Blackfire.pp:9 on node local.puphpet
==> default: Wrapped exception:
==> default: exception object expected
==> default: Error: exception object expected at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Blackfire.pp:9 on node local.puphpet
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Config.yaml:
```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local.puphpet
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_s1ja7g69m72f:
                    host: '8750'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_bqrefbo5dy96:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_vc6tkr4xqyxt:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_9uxex5c4cpsw:
                    location: /
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_wbofjy565b5w:
                    location: '~ \.php$'
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_ztgg5wq63qqo:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '443'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sfdzokvqdd38:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_qk1seuehet4a:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_8nqrdr68an9o:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '1'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: On
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_qyzdr2n9639s:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_b7rz5v8s5fo6:
            name: dbname
            sql: ''
    grants:
        mysqlng_pnng2ygborfu:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by jtreminio** [comment] 2015-05-23 00:41
dupe of #1627

**Closed by jtreminio** 2015-05-23 00:41 UTC
