### ISSUE TITLE
default: Error: Could not find dependency File[/etc/php5/fpm/php-fpm.conf

### ISSUE THREAD

**Issue by leknoppix** [puphpet/puphpet#1570] opened 2015-04-23 17:44 UTC
I'm trying to install a debian vagrant (LAMP) with vagrant up but I have this error:

==> default: Error: Could not find dependency File[/etc/php5/fpm/php-fpm.conf] for Augeas[global/pid: /run/php-fpm.pid] at /tmp/vagrant-puppet/modules-8c72b94166dd71ed47b4676a0b5fb0ec/puphpet/manifests/php/fpm/ini.pp:73
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Can you help me?
Thank

**Comment by jtreminio** [comment] 2015-04-23 21:14
Dupe of #1569 - fix is incoming.

**Closed by jtreminio** 2015-04-23 21:14 UTC
