### ISSUE TITLE
DHCP support please

### ISSUE THREAD

**Issue by fsieduc** [puphpet/puphpet#1299] opened 2014-12-30 10:45 UTC
Could you please add DHCP support to your app ?

For eg: Vagrantfile
  if data['vm']['network']['private_network'].to_s != ''
    config.vm.network 'private_network', ip: "#{data['vm']['network']['private_network']}"
  else
    config.vm.network "public_network", type: "dhcp"
  end

**Comment by jtreminio** [comment] 2015-03-11 08:07
Dupe of #1296

**Closed by jtreminio** 2015-03-11 08:07 UTC
