### ISSUE TITLE
Problem with Centos 6.5

### ISSUE THREAD

**Issue by coolfarmer** [puphpet/puphpet#2416] opened 2016-08-28 21:32 UTC
```
==> vm3: Error: Could not find a suitable provider for mysql_user
==> vm3: Error: Could not find a suitable provider for mysql_database
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I'm on a fresh new Windows 10, fresh new VMware Workstation 12 and Vagrant 1.8.5.
Ubuntu works with no problem, but not Centos.

I try some things but nothing work.

I think the package is broken.

**Comment by po2go-sean** [comment] 2016-08-29 16:24
Related: (trying to manually install MySQL on CentOS 6)

http://apt.sw.be/redhat/el6/en/x86_64/extras/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: repoforgeextras. Please verify its path and try again

**Comment by po2go-sean** [comment] 2016-08-29 16:27
Duplicate of Issue #2408  (You can find a fix there.)

**Comment by natenolting** [comment] 2016-09-02 16:54
@po2go-sean is right on, that hot fix should fix the issue. https://github.com/sugalvojau/veikt.dev/commit/edd942260c22803801f598df890b9caa044aead3

**Comment by jtreminio** [comment] 2016-10-05 20:11
Fixed in the latest round of puppet refactoring: https://github.com/puphpet/puppet-puphpet/tree/master/manifests/mysql

**Closed by jtreminio** 2016-10-05 20:11 UTC
