### ISSUE TITLE
Permissions issue: OS X, NFS

### ISSUE THREAD

**Issue by oflannabhra** [puphpet/puphpet#1378] opened 2015-02-17 17:01 UTC
I've got a couple issues going on. My web apps don't have write access to the shared folders. Here's my configurations:

Software | Version
------------|-----------
Vagrant | 1.7.2
OS X | 10.10.2

I'm using NFS to mount my shared folder, with 

environment / directory | user / group | permissions
----------|----------|-----------
OS X  `/root` | `meph / staff` | 755
Vagrant `/var/www` | `www-data / www-data` | 755
Vagrant `/mnt/vagrant-XXXX` | **`www-data / games`** | 755
httpd.conf settings | `www-data / www-data` |

If I echo through a php process `whoami`, I get `apache`, which i'm hoping is a member of the `www-data` group, but I'm guessing is *not* a member of the **games** group (I have no idea where this is even coming from). I know this is a configuration issue on my end, I'm just not sure I know where. Below is my `config.yml`

```yaml
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                B5zhRzYT5exG:
                    host: '6269'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            VQn0Ihw1oqWu:
                owner: www-data
                group: www-data
                source: /Users/meph/Documents/Projects/web
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        2eyatdmfil0h:
            servername: site2.dev
            serveraliases:
                - site2.dev
            docroot: /var/www/site2
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                xdkcdrzmqaus:
                    provider: directory
                    path: /var/www/site2
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        2eyat123l0h:
            servername: site1.dev
            serveraliases:
                - site1.dev
            docroot: /var/www/site1
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                xdkcdrzmqAU3:
                    provider: directory
                    path: /var/www/site1
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        2gwyk8pqppp4:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/New_York
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        ZiIS8ru9BNLb:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        h53ULYwPx8L3:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        IMRcrWGZSjqz:
            grant:
                - ALL
            name: ***
            host: localhost
            user: ***
            password: ***
            sql_file: ''
        LnSWf2rGfqBt:
            grant:
                - ALL
            name: ***
            host: localhost
            user: ***
            password: ***
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
and the relevant portion of the `Vagrantfile`
```
data['vm']['synced_folder'].each do |i, folder|
    if folder['source'] != '' && folder['target'] != ''
      sync_owner = !folder['sync_owner'].nil? ? folder['sync_owner'] : 'www-data'
      sync_group = !folder['sync_group'].nil? ? folder['sync_group'] : 'www-data'

      if folder['sync_type'] == 'nfs'
        if Vagrant.has_plugin?('vagrant-bindfs')
          config.vm.synced_folder "#{folder['source']}", "/mnt/vagrant-#{i}", id: "#{i}", type: 'nfs'
          config.bindfs.bind_folder "/mnt/vagrant-#{i}", "#{folder['target']}", user: sync_owner, group: sync_group
        else
          config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}", type: 'nfs'
        end
```

**Comment by m-reiniger** [comment] 2015-02-19 11:22
I had the same Problem. I tracked it down to a naming issue.

in the config.yml ther is the synced_folder section:

synced_folder:
            VQn0Ihw1oqWu:
                owner: www-data
                group: www-data
                source: /Users/meph/Documents/Projects/web
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'

You can configure the owner and group here for each Folder you want to bind to your vagrant environment.

**owner**: www-data
**group**: www-data

The problem is, in the Vagrantfile, those entries are expected to have a different name:

sync_owner = !folder['**sync_owner**'].nil? ? folder['**sync_owner**'] : 'www-data'
sync_group = !folder['**sync_group**'].nil? ? folder['**sync_group**'] : 'www-data'

for a quick fix just rename either the property names in your config.yml or in the Vagrantfile.

But this is a bug, should be fixed by puphet owner.

Hope this helps.

**Comment by beporter** [comment] 2015-02-20 16:46
This is a result of #1356.

**Comment by oflannabhra** [comment] 2015-02-20 16:54
That is an issue, but it looks like the values are (coincidentally) being assigned correctly. Shouldn't the `www-data` group have write access to the shared folder, as apache runs under that group?

**Comment by beporter** [comment] 2015-02-20 16:57
I would think so, yeah.

All I know is that I've had tons of permission issues over the years, especially when SSHing into the box as the default `vagrant` user. :shrug: It's just another thread to follow. :sweat:

**Comment by beporter** [comment] 2015-02-23 14:52
Our of curiosity, what are the actual group IDs for the groups you listed in the OP? I wonder if the IDs match but the group names assigned to those IDs don't match between the host and the guest. That'd at least be a clue as to what's not getting set where.

**Comment by jtreminio** [comment] 2015-03-06 00:56
Thanks guys, at the end of the day it turns out I don't quite know what I'm doing, but with a strong community everything gets fixed!

**Closed by jtreminio** 2015-03-06 00:56 UTC
