### ISSUE TITLE
Failed to upload a file to the guest VM via SCP due to a permissions error

### ISSUE THREAD

**Issue by kbemelmans** [puphpet/puphpet#1839] opened 2015-08-12 07:50 UTC
Setup: Mac OSX 10.10.4, Vagrant 1.7.2, virtualbox 4.3.26

Problem:

An initial vagrant up runs fine, it takes quite a while to provision but when it's done the system is up and running. When I do a "vagrant halt" and a "vagrant up" again, I get this error:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'puphpet/centos65-x64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 9105 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /var/folders/mh/f423t16x0_j6x221_5pyc3n80000gn/T/vagrant20150812-12672-1mzav3t
Dest: /tmp/vagrant-network-entry_1
```

My config.yml

```
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: development.box
        memory: '2048'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_ruzok1ju7wev:
                    host: '9105'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_p2r1jj0avx9m:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_uj2nkvv86vyw:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_fn1r2k0r966o:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_9ufawkny6nf1:
                    location: '~ \.php$'
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_jb8br25m776w:
            servername: dev.local
            docroot: /var/www/vhosts/dev.local
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_db0dm2hpwuwy:
                    path: /var/www/vhosts
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5nnoz8p8hq05:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
            - bcmath
            - gd
            - opcache
        pear: {  }
        pecl:
            - memcache
            - memcached
            - imagick
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Brussels
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_3mueoho8zf52:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '1'
wpcli:
    install: '1'
    version: v0.19.0
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - bower
        - grunt
        - grunt-cli
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: mysql
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_nfxbqxbp4s6l:
            name: dev
            password: dev
    databases:
        mysqlnd_lp7pus6h1vyd:
            name: dbname
            sql: ''
    grants:
        mysqlng_vv21sld6cgjj:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_dtub8ehzmmw0:
            name: dev
            password: dev
    databases:
        mariadbnd_1cjypea66fke:
            name: dbname
            sql: ''
    grants:
        mariadbng_rfrlfndie7zm:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by segadora** [comment] 2015-08-15 18:32
+1 same issue

**Comment by segadora** [comment] 2015-08-15 19:01
https://github.com/mitchellh/vagrant/issues/2804
https://github.com/mitchellh/vagrant/issues/2994

do 

```
sudo chmod -R 777 /tmp
```

on vagrant and it will fix it.

Of some reason /tmp is not writeable.

**Comment by xiris** [comment] 2015-08-15 20:29
+1, same issue here.

I "hardfix" executing a script to give the permission when the guest OS (vagrant) boot.

Inside your guest OS (vagrant) create the file **fix-tmp-permission** and put the instruction mentioned by @segadora 
> sudo vim /etc/init.d/fix-tmp-permission

```shell
 #!/bin/sh
 sudo chmod -R 777 /tmp
```

Change the permission:
> sudo chmod +x /etc/init.d/fix-tmp-permission

Now you can exit and reload, halt, up, etc ...

Ps.: Just a hardfix

**Comment by emielmolenaar** [comment] 2015-09-11 08:31
==> default: Notice: /Stage[main]/Puphpet_mariadb/File[/tmp]/owner: owner changed 'root' to 'mysql'
==> default: Notice: /Stage[main]/Puphpet_mariadb/File[/tmp]/mode: mode changed '0777' to '0775'
==> default: Info: /Stage[main]/Puphpet_mariadb/File[/tmp]: Scheduling refresh of Service[mysqld]
==> default: Info: /Stage[main]/Puphpet_mariadb/File[/tmp]: Scheduling refresh of Service[mysqld]

That's the cause.

**Comment by mikeshawdev** [comment] 2015-09-29 14:01
Is there a fix for this?

**Comment by segadora** [comment] 2015-09-29 14:04
as @emielmolenaar says it seems to be related to that, so I guess if you choose another db?

**Comment by mikeshawdev** [comment] 2015-09-30 10:40
@segadora aye I've been using MySQL instead on my dev environments, but would like to be able to use MariaDB (especially if live is using MariaDB) just to be as close to production setup as possible

**Comment by segadora** [comment] 2015-09-30 10:44
@mikeshawdev I think the problem is related to https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/MariaDb.pp#L77-L87 I will try to fix it, and make a pull request later.

**Comment by mikeshawdev** [comment] 2015-09-30 12:45
@segadora sweet, cheers!

**Comment by segadora** [comment] 2015-09-30 16:32
Go to MariaDb.pp
Find:

```
  # prevent problems with being unable to create dir in /tmp
  if ! defined(File[$override_options['mysqld']['tmpdir']]) {
    file { $override_options['mysqld']['tmpdir']:
      ensure  => directory,
      owner   => $mariadb_user,
      group   => $mysql::params::root_group,
      mode    => '0775',
      require => Class['mysql::client'],
      notify  => Service[$settings['service_name']]
    }
  }
```

and delete the lines.

After that, use vagrant destroy and vagrant up. The issue will be gone.

**Comment by segadora** [comment] 2015-09-30 16:32
@mikeshawdev solution posted

**Comment by mikeshawdev** [comment] 2015-10-01 09:24
@segadora brilliant, big thanks!

**Closed** 2015-10-05 04:27 UTC
