### ISSUE TITLE
Conflict using NFS+BINDFS with APACHE/NGINX

### ISSUE THREAD

**Issue by akomm** [puphpet/puphpet#1929] opened 2015-10-01 08:46 UTC
This: [archive/puphpet/puppet/nodes/Apache.pp#L34-L50](https://github.com/puphpet/puphpet/blob/8bae8a00101d49e303731af46f4a3aa6b889a333/archive/puphpet/puppet/nodes/Apache.pp#L34-L50)

Cause errors and break provisioning of dependencies, when nfs and bindfs are used, because 'www-data' is hard-coded here. No matter whether you set after: :provision for bindfs in vagrant-local setting or not, it fails with permission denied and follow-up failed because of failed dependency.

*edit*
Now tested it with nginx, same issue.

**Comment by akomm** [comment] 2015-10-01 10:41
Looks like `after: provision` option for bindfs.bind_folder works with nginx (not apache) in this case, but when I add after: provision, all the sudden the options on config.bindfs.bind_folder invokation are not converted properly to bindfs options, so I get back to this issue: 

https://github.com/puphpet/puphpet/issues/1920

Resulting in 
```
The bind command `bindfs --perms=u=rwx:g=rwx:o=r --user=xxx --group=xxx /mnt/vagrant-xxx /var/www` failed to run!
```
Because --user and --group are deprecated. When I remove after, I get the first problem on provision. 

This is so frustrating.  Fix problem 1, cause problem 2, fix problem 2, fix for problem 1 broken... Not to mention tons of other issues, like php5-fpm with by default enabled opcache enabled - known to have many issues this is getting to "not usable at all" state. Feels like "phileas fogg" adventures here.

**Comment by akomm** [comment] 2015-10-01 16:49
Looks like the new issue happen because the mount point is not empty. I expected the message displayed to be STDOUT/STDERR of bindfs command, but it was not. 

To solve the provisioning error, as mentioned I'v modified vagrantfile-local to bind after provisioning. But in that case the vhost document roots were created and populated with "dummy" files making bindfs fail because the mount point is not empty.

adding fuse-option `o: 'nomount'` fixed that. The core issue remains, but can be workaround this way (at least on nginx)

**Comment by jtreminio** [comment] 2015-11-30 06:59
Thanks, merged in!

**Closed** 2015-11-30 06:59 UTC

**Comment by orthes** [comment] 2016-01-13 15:32
Hi! Folder syncing with NFS+BINDFS stopped working for me after this change. `vagrant up` runs without any error, but `/var/www/my-project` is empty. Changing `sync_type` from `nfs` to `default` fixed it, so the problem is apparently in `nfs` implementation. I tracked it down to `after: :provision` option. When I remove it from https://github.com/puphpet/puphpet/blob/master/archive/puphpet/vagrant/Vagrantfile-local#L93, everything works again correctly.

**Comment by akomm** [comment] 2016-02-03 08:04
What version of bindfs do you have? You also have linked to the master branch which is moving, so I think the line is not the one you wanted to point to.

**Comment by chonny** [comment] 2016-06-28 15:01
Hello @orthes could be so kind to provide more info please? I am trying to fix the same issue.
